[character]
success_symbol = "[λ](bold bright-purple) "
error_symbol = "[λ](bold red) "

[directory]
truncation_symbol = ".../"
fish_style_pwd_dir_length = 3

[directory.substitutions]
"/Volumes/Code" = "~/Code"
